
s = set()
n = int(input("Enter number 1:\n"))
s.add(int(n))
n = int(input("Enter number 2:\n"))
s.add(int(n))
n = int(input("Enter number\n"))
s.add(int(n))
n = int(input("Enter number\n"))
s.add(int(n))
n = int(input("Enter number\n"))
s.add(int(n))
n = int(input("Enter number\n"))
s.add(int(n))
n = int(input("Enter number\n"))
s.add(int(n))
n = int(input("Enter number\n"))
s.add(int(n)) 
print(s)

