#What if the names of two friends are same in 
d = {}
Name = input("enter name of friends:")
language = input("Enter thr language :")
d.update({Name: language})
Name = input("enter name of friends:")
language = input("Enter thr language :")
d.update({Name: language})
Name = input("enter name of friends:")
language = input("Enter thr language :")
d.update({Name: language})
Name = input("enter name of friends:")
language = input("Enter thr language :")
d.update({Name: language})
Name = input("enter name of friends:")
language = input("Enter thr language :")
d.update({Name: language}) 
print(d)